<a href="https://colab.research.google.com/github/shubheshswain91/Deep_Learning/blob/master/pytorch_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
x = torch.Tensor([5,2])
y= torch.Tensor([2,1])

In [3]:
print(x*y)

tensor([10.,  2.])


In [4]:
x = torch.zeros([2,5])

In [5]:
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [6]:
print(x.shape)

torch.Size([2, 5])


In [8]:
y = torch.rand([2,5])

In [9]:
y

tensor([[0.7983, 0.6918, 0.1978, 0.9301, 0.6448],
        [0.2440, 0.8987, 0.8625, 0.8311, 0.1125]])

In [10]:
y.view([1,10])

tensor([[0.7983, 0.6918, 0.1978, 0.9301, 0.6448, 0.2440, 0.8987, 0.8625, 0.8311,
         0.1125]])

In [12]:
y = y.view([1,10])

In [13]:
y

tensor([[0.7983, 0.6918, 0.1978, 0.9301, 0.6448, 0.2440, 0.8987, 0.8625, 0.8311,
         0.1125]])